name: Commit workflow
on:
  push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build packages & website
        run: npm run build

      - name: Install Playwright
        run: npx playwright install

      - name: Test
        run: npm run test:once

  release-please:
    name: Release Please
    needs: test
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{ steps.release.outputs.paths_released }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          command: manifest
          monorepo-tags: true

  deploy:
    if: contains(needs.release-please.outputs.paths_released, 'apps/website')
    name: Deploy to figx.io
    needs: release-please
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build figx.io
        run: npm run build

      - name: Deploy to cloudflare
        uses: cloudflare/wrangler-action@3.0.0
        with:
          workingDirectory: ./apps/website
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: 3.5.0
          command: pages deploy 'dist' --project-name=figx --branch=main

  publish-core:
    if: contains(needs.release-please.outputs.paths_released, 'packages/core')
    name: Publish @figx-io/core to NPM
    needs: release-please
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build @figx-io/core
        run: npm run build:core

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN  }}
          package: packages/core
          access: public
