name: Release workflow
on:
  pull_request:
    paths:
      - packages/ui

jobs:
  publish-ui:
    name: Publish @figx-io/ui to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build @figx-io/core & @figx-io/ui
        run: npm run build:packages

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN  }}
          package: packages/ui
          access: public
